### ISSUE TITLE
terraform-provider-flux_v1.0.0-rc.4 plugin crashes when importing flux_bootstrap_git.this

### ISSUE THREAD

**Issue by audunsolemdal** [fluxcd/terraform-provider-flux#488]
Unsure if the root cause is directly related to #487 and similar issues or not, so creating a separate issue.

I am attempting to run terraform import on an existing bootstrapped cluster which is created by an older version of the flux terraform provider, `data "flux_sync" "this`. and related resources.

Terraform version 1.4.6
flux provider version terraform-provider-flux_v1.0.0-rc.4. 
Current in-cluster flux config is on  Version v1.0.0-rc.3

Relevant tf config:

```hcl
provider "flux" {}

locals {
  base = file("${path.module}/fluxcd/templates/kustomization-base.yaml")
}

resource "flux_bootstrap_git" "this" {
  path                   = "clusters/${var.cluster_id}"
  network_policy         = false # some issues on AKS if set to true, likely due to git auth proxy.
  kustomization_override = local.base
  toleration_keys = [
    "CriticalAddonsOnly"
  ]
  disable_secret_creation = false # tbd
}

```

Output:
```

terraform import -var-file=config-dev.tfvars flux_bootstrap_git.this flux-system
Acquiring state lock. This may take a few moments...
flux_bootstrap_git.this: Importing from ID "flux-system"...

(...)
(various sucessful read operations)
(...)
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ValidateDataResourceConfig call. The plugin logs
│ may contain more details.
╵

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ValidateDataResourceConfig call. The plugin logs
│ may contain more details.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).ImportResourceState request was cancelled.
╵

Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-flux_v1.0.0-rc.4 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a95bd8]

goroutine 13 [running]:
github.com/fluxcd/terraform-provider-flux/internal/provider.(*providerResourceData).GetKubernetesClient(0x416090?)
	github.com/fluxcd/terraform-provider-flux/internal/provider/provider_resource_data.go:64 +0x18
github.com/fluxcd/terraform-provider-flux/internal/provider.(*bootstrapGitResource).ImportState(0xc000130050, {0x221e8c0, 0xc000694570}, {{0xc0004e24a0?, 0x1f44e25?}}, 0xc000526960)
	github.com/fluxcd/terraform-provider-flux/internal/provider/resource_bootstrap_git.go:667 +0x6c
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ImportResourceState(0xc000414840, {0x221e8c0, 0xc000694570}, 0xc0000a9c80, 0xc0004fd620)
	github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/fwserver/server_importresourcestate.go:104 +0x462
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ImportResourceState(0xc000414840, {0x221e8c0?, 0xc000694420?}, 0xc0005101e0)
	github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/proto6server/server_importresourcestate.go:44 +0x30b
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ImportResourceState(0xc0000c15e0, {0x221e8c0?, 0xc00050fad0?}, 0xc0005266e0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/tf6server/server.go:846 +0x1f6
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ImportResourceState_Handler({0x1e21060?, 0xc0000c15e0}, {0x221e8c0, 0xc00050fad0}, 0xc00036d180, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:403 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00052a[78](https://github.com/myorg/myrepo/actions/runs/5132276480/jobs/9233362858#step:11:79)0, {0x2228178, 0xc00044a680}, 0xc00041c240, 0xc00064[79](https://github.com/myorg/myrepo/actions/runs/5132276480/jobs/9233362858#step:11:80)20, 0x31822d8, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1340 +0xd33
google.golang.org/grpc.(*Server).handleStream(0xc00052a7[80](https://github.com/myorg/myrepo/actions/runs/5132276480/jobs/9233362858#step:11:81), {0x222[81](https://github.com/myorg/myrepo/actions/runs/5132276480/jobs/9233362858#step:11:82)78, 0xc00044a680}, 0xc00041c240, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-flux_v1.0.0-rc.4 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

**Comment by phillebaba** [comment]
This issue you are facing is caused by the provider not containing any Git or Kuberentes configuration. I thought i fixed the panic that you are seeing but apparently not. Will have a look at that.

**Comment by audunsolemdal** [comment]
Thanks for clarifying. Originally I only wanted to specify the `git` block, but this was not allowed, so attempted removing both blocks.
